(in-package #:cl-lsp)

;;;; -- URI and JSON Boundaries --

(-> test-lsp-file-uris () null)
(defun test-lsp-file-uris ()
  "Exercise UTF-8 URI segments, drive letters, UNC hosts, and native paths."
  (dolist (entry '(("C:\\src\\a b#%.lisp" "file:///C:/src/a%20b%23%25.lisp")
                   ("D:\\žluť\\😀.txt" "file:///D:/%C5%BElu%C5%A5/%F0%9F%98%80.txt")
                   ("\\\\server\\share\\a b.txt" "file://server/share/a%20b.txt")))
    (tests--assert (string= (second entry) (lsp--windows-path-uri (first entry)))
                   "Windows paths retain drive and UNC URI structure"))
  (tests--assert (string= "/a%20b/%C5%BE%23%25%5C.txt"
                          (lsp--encode-uri-path "/a b/ž#%\\.txt"))
                 "path segments encode literal backslashes and reserved characters")
  (with-test-directory (root)
    (let ((uri (lsp-path-uri (merge-pathnames "a b.txt" root))))
      (tests--assert (and (uiop:string-prefix-p "file:///" uri)
                          (uiop:string-suffix-p uri "a%20b.txt"))
                     "native absolute path produces a file URI")))
  nil)

(-> test-lsp-project-roots () null)
(defun test-lsp-project-roots ()
  "Select the nearest marker directory without leaving the workspace."
  (with-test-directory (root)
    (let* ((root      (truename root))
           (workspace (merge-pathnames "workspace/" root))
           (project   (merge-pathnames "project/" workspace))
           (nested    (merge-pathnames "packages/client/" project))
           (file      (merge-pathnames "main.ts" nested)))
      (tests--write-text file "")
      (tests--write-text (merge-pathnames "package.json" project) "{}")
      (tests--write-text (merge-pathnames "Cargo.toml" root) "")
      (ensure-directories-exist (merge-pathnames ".git/" nested))
      (flet ((project-root (path &rest markers)
               "Return the project root for PATH under WORKSPACE and MARKERS."
               (lsp-project-root path workspace markers)))
        (tests--assert (equal project (project-root file "package.json"))
                       "the nearest ancestor holding a marker file is selected")
        (tests--assert (equal nested (project-root file ".git" "package.json"))
                       "a marker directory counts and nearer markers win")
        (tests--assert (equal project (project-root project "package.json"))
                       "a directory pathname is searched from itself")
        (tests--assert (equal workspace (project-root file "Cargo.toml"))
                       "markers above the workspace are never used")
        (tests--assert (equal workspace (project-root file "*.json"))
                       "markers are literal names, not wildcards")
        (tests--assert (equal workspace
                              (project-root (merge-pathnames "elsewhere.ts" root)
                                            "Cargo.toml"))
                       "paths outside the workspace fall back to the workspace")
        (let ((*lsp-maximum-root-depth* 2))
          (tests--assert (equal workspace (project-root file "package.json"))
                         "the upward search is bounded")))))
  nil)

(-> test-lsp-json-boundaries () null)
(defun test-lsp-json-boundaries ()
  "Accept one framed JSON object and reject anything else, including deep nesting."
  (tests--assert (json-object-p (lsp--decode-message " {\"a\":[1]} "))
                 "a frame holding one JSON object decodes")
  (let ((deep (format nil "{\"a\":~A1~A}"
                      (make-string 70 :initial-element #\[)
                      (make-string 70 :initial-element #\]))))
    (dolist (source (list "{}{}" "{} trailing" "[]" "null" "{\"unterminated\":\"x}" deep))
      (tests--assert (handler-case (progn (lsp--decode-message source) nil)
                       (lsp-error () t))
                     "frames contain exactly one complete, bounded JSON object")))
  nil)
