(in-package #:cl-lsp)

;;;; -- File Operation Registration Filters --

(-> lsp-file-filter--expand-braces (string) list)
(defun lsp-file-filter--expand-braces (pattern)
  "Expand bounded brace alternatives in an LSP glob PATTERN."
  (when (> (length pattern) 1024)
    (lsp-edit--invalid "glob" "File operation glob exceeds 1024 characters."))
  (let ((results nil))
    (labels ((expand (source)
               (when (>= (length results) 128)
                 (lsp-edit--invalid "glob" "File operation glob has too many alternatives."))
               (let ((open nil) (close nil) (depth 0) (escaped nil) (in-class nil)
                     (separators nil))
                 (loop for character across source for index from 0
                       do (cond
                            (escaped (setf escaped nil))
                            ((char= character #\Backslash) (setf escaped t))
                            ((char= character #\[) (setf in-class t))
                            ((char= character #\]) (setf in-class nil))
                            (in-class nil)
                            ((char= character #\{)
                             (when (zerop depth) (setf open index))
                             (incf depth))
                            ((char= character #\})
                             (when (zerop depth) (lsp-edit--invalid "glob" "Unmatched closing brace."))
                             (decf depth)
                             (when (zerop depth) (setf close index) (return)))
                            ((and (= depth 1) (char= character #\,)) (push index separators))))
                 (when (and open (null close))
                   (lsp-edit--invalid "glob" "Unclosed brace alternative."))
                 (if open
                     (loop with start = (1+ open)
                           for end in (append (nreverse separators) (list close))
                           do (expand (concatenate 'string (subseq source 0 open)
                                                  (subseq source start end)
                                                  (subseq source (1+ close))))
                              (setf start (1+ end)))
                     (push source results)))))
      (expand pattern))
    (nreverse results)))

(-> lsp-file-filter--glob-p (string string) boolean)
(defun lsp-file-filter--glob-p (pattern path)
  "Match *, **, ?, braces and character sets against a slash-separated PATH."
  (some
   (lambda (source)
     (let ((memo (make-hash-table :test #'equal))
           (size (length source))
           (length (length path)))
       (labels ((match (pattern-index text-index)
                  (let ((key (cons pattern-index text-index)))
                    (multiple-value-bind (result present-p) (gethash key memo)
                      (if present-p result
                          (setf (gethash key memo) (step-match pattern-index text-index))))))

                (step-match (pattern-index text-index)
                  (when (= pattern-index size) (return-from step-match (= text-index length)))
                  (let ((character (char source pattern-index)))
                    (cond
                      ((char= character #\*)
                       (let* ((double (and (< (1+ pattern-index) size)
                                           (char= (char source (1+ pattern-index)) #\*)))
                              (next (+ pattern-index (if double 2 1))))
                         (or (match next text-index)
                             (and double (< next size) (char= (char source next) #\/)
                                  (match (1+ next) text-index))
                             (and (< text-index length)
                                  (or double (char/= (char path text-index) #\/))
                                  (match pattern-index (1+ text-index))))))
                      ((char= character #\?)
                       (and (< text-index length) (char/= (char path text-index) #\/)
                            (match (1+ pattern-index) (1+ text-index))))
                      ((char= character #\[)
                       (let ((end (position #\] source :start (1+ pattern-index))))
                         (unless end (lsp-edit--invalid "glob" "Unclosed character class."))
                         (let* ((start (1+ pattern-index))
                                (negated (and (< start end) (find (char source start) "!^")))
                                (found nil))
                           (when negated (incf start))
                           (when (= start end) (lsp-edit--invalid "glob" "Empty character class."))
                           (when (< text-index length)
                             (loop with target = (char path text-index)
                                   for index from start below end
                                   do (if (and (< (+ index 2) end)
                                               (char= (char source (1+ index)) #\-))
                                          (progn
                                            (when (char<= (char source index) target
                                                          (char source (+ index 2)))
                                              (setf found t))
                                            (incf index 2))
                                          (when (char= target (char source index)) (setf found t))))
                             (and (char/= (char path text-index) #\/)
                                  (if negated (not found) found)
                                  (match (1+ end) (1+ text-index)))))))
                      (t
                       (when (char= character #\Backslash)
                         (incf pattern-index)
                         (when (= pattern-index size)
                           (lsp-edit--invalid "glob" "Dangling glob escape."))
                         (setf character (char source pattern-index)))
                       (and (< text-index length) (char= character (char path text-index))
                            (match (1+ pattern-index) (1+ text-index))))))))
         (match 0 0))))
   (lsp-file-filter--expand-braces pattern)))

(-> lsp-file-filter--matches-p (json-object string (option function)) boolean)
(defun lsp-file-filter--matches-p (filter uri file-kind)
  "Match a registration FILTER against URI using FILE-KIND only when required."
  (lsp-edit--object filter "fileOperationFilter")
  (let* ((pattern (lsp-edit--object (json-get filter "pattern") "pattern"))
         (glob (lsp-edit--string (json-get pattern "glob") "glob"))
         (scheme (gethash "scheme" filter))
         (matches (gethash "matches" pattern))
         (options (gethash "options" pattern))
         (parsed (handler-case (quri:uri uri)
                   (error () (lsp-edit--invalid "uri" "Cannot parse file operation URI."))))
         (path (handler-case
                   (quri:url-decode
                    (with-output-to-string (output)
                      (loop for character across (or (quri:uri-path parsed) "")
                            do (if (char= character #\+)
                                   (write-string "%2B" output)
                                   (write-char character output)))))
                 (error () (lsp-edit--invalid "uri" "Cannot decode file operation URI path.")))))
    (when (and scheme (not (stringp scheme)))
      (lsp-edit--invalid "scheme" "Filter scheme must be a string."))
    (when (and matches (not (member matches '("file" "folder") :test #'equal)))
      (lsp-edit--invalid "matches" "Filter matches must be file or folder."))
    (when options
      (lsp-edit--object options "options")
      (multiple-value-bind (ignore-case present-p) (gethash "ignoreCase" options)
        (when (and present-p (not (member ignore-case (list t (json-false)))))
          (lsp-edit--invalid "ignoreCase" "Glob ignoreCase must be a boolean."))))
    (and (or (null scheme) (equalp scheme (quri:uri-scheme parsed)))
         (if (and options (json-get options "ignoreCase"))
             (lsp-file-filter--glob-p (string-downcase glob) (string-downcase path))
             (lsp-file-filter--glob-p glob path))
         (or (null matches)
             (progn
               (unless file-kind
                 (lsp-edit--invalid "fileKind" "A file/folder filter requires a caller file-kind callback."))
               (let ((kind (funcall file-kind uri)))
                 (unless (member kind '(:file :folder))
                   (lsp-edit--invalid "fileKind" "File-kind callback must return :FILE or :FOLDER."))
                 (equal matches (ecase kind (:file "file") (:folder "folder")))))))))
